import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './styles/globals.css';
import Header from './shared/components/ui/header';
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    //@ts-ignore
    <ClerkProvider>
      <html lang='en'>
        <body className={inter.className}>
          <div className='flex flex-col h-screen w-full'>
            <Header />
            <div className='grow flex-1 overflow-y-auto h-[calc(100vh-var(--header-height)]'>
              {children}
            </div>
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
